name: Tender Buttons Illustrated
pygments: true
author: Sadie Starnes
description:
permalink: /:title/
prose:
  rooturl: "_posts"
  siteurl: "http://tenderbuttons.github.io"
  media: "resources"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: " "
      - name: "image"
        field:
          element: "text"
          label: "Photo URL"
          value: "/resources/ "
