name: Tender Buttons Illustrated
pygments: true
author: Sadie Starnes
description:
permalink: /:title/

prose:
  rooturl: "_posts"
  siteurl: "http://tenderbuttons.github.io"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: " "
